apiVersion: infisical-issuer.infisical.com/v1alpha1
kind: Issuer
metadata:
  name: apolo-pki-issuer
  namespace: corebank-apps
spec:
  url: http://infisical-lb.infisical.svc.cluster.local
  projectId: "01bb4bb3-1af3-4919-a482-8d2d99c69b6b"
  certificateTemplateName: "corebank-client-template"
  authentication:
    universalAuth:
      clientId: "23c03c93-6fd8-4522-9914-a1aa4a30f869"
      secretRef:
        name: infisical-operator-auth
        key: clientSecret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: corebank-mtls-identity
  namespace: corebank-apps
spec:
  secretName: corebank-client-tls-secret
  commonName: corebank.service.internal
  dnsNames:
    - corebank.corebank-namespace.svc.cluster.local
  duration: 24h
  renewBefore: 6h
  issuerRef:
    name: apolo-pki-issuer
    kind: Issuer
    group: infisical-issuer.infisical.com
