replicaCount: 1

image:
  repository: infisical/infisical
  pullPolicy: IfNotPresent
  tag: "v0.81.0"

serviceAccount:
  create: true

service:
  type: ClusterIP
  port: 8080

# Desativa explicitamente os sub-charts internos
postgresql:
  enabled: false

redis:
  enabled: false

mongodb:
  enabled: false

# Configuração para as versões estáveis atuais do chart
global:
  database:
    url: "postgresql://postgres:infisicalpassword@infisical-postgresql:5432/infisical?sslmode=disable"
  redis:
    url: "redis://:redispassword@infisical-redis-master:6379/0"
  encryptionKey: "12345678901234567890123456789012"
  jwtSignSecret: "super-secret-jwt-sign-key"
  jwtRefreshSecret: "super-secret-jwt-refresh-key"
  authSecret: "super-secret-auth-key"
